### Variáveis
@baseUrl = http://localhost:8080

### Inserir novo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Inserir segundo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Jane Smith",
  "email": "jane.smith@example.com",
  "password": "securepass456"
}

### Buscar usuário por email
GET {{baseUrl}}/users/email?email=john.doe@example.com

### Listar todos os jogos
GET {{baseUrl}}/games

### Listar listas de jogos
GET {{baseUrl}}/lists

### Buscar jogo por ID
GET {{baseUrl}}/games/id?id=1

### Buscar jogo por título
GET {{baseUrl}}/games/title?title=Mass